name: Deploy Multy App
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Specify docker credentials
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker images
        run: docker build -t treest/react-test -f ./client/Dockerfile.dev ./client
      - name: Run tests
        run: docker run -e CI=true treest/react-test npm test
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Specify docker credentials
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build client
        run: docker build -t treest/multi-client ./client
      - name: Build nginx
        run: docker build -t treest/multi-nginx ./nginx
      - name: Build server
        run: docker build -t treest/multi-server ./server
      - name: Build worker
        run: docker build -t treest/multi-worker ./worker

      - name: Push client to Hub
        run: docker push treest/multi-client
      - name: Push nginx to Hub
        run: docker push treest/multi-nginx
      - name: Push server to Hub
        run: docker push treest/multi-server
      - name: Push worker to Hub
        run: docker push treest/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-450730742269
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
  